classifier: logistic
dataset: meta-mini-imagenet
encoder: convnet4
encoder_args:
  bn_args:
    track_running_stats: false
epoch: 300
inner_args:
  classifier_lr: 0.01
  encoder_lr: 0.01
  first_order: false
  frozen:
  - bn
  n_step: 5
optimizer: adam
optimizer_args:
  lr: 0.001
train:
  image_size: 84
  n_batch: 200
  n_episode: 4
  n_query: 15
  n_shot: 1
  n_way: 5
  normalization: false
  split: meta-train
  transform: null
val:
  image_size: 84
  n_batch: 200
  n_episode: 4
  n_query: 15
  n_shot: 1
  n_way: 5
  normalization: false
  split: meta-val
  transform: null
