encoder_args:
  bn_args:
    track_running_stats: False

inner_args:
  n_step: 5
  encoder_lr: 0.01
  classifier_lr: 0.01
  first_order: False  # set to True for FOMAML
  frozen:
    - bn

optimizer: adam
optimizer_args:
  lr: 0.01